// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdleState } from "./IdleState";
import type { JumpIdleState } from "./JumpIdleState";

export type CharacterState = { Idle: IdleState } | "Walk" | "Falling" | { JumpIdle: JumpIdleState } | "JumpWalking";