// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Quat } from "./Quat";
import type { Vec3 } from "./Vec3";

export interface Translation { p: Vec3, q: Quat, }