// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Quat } from "./Quat";
import type { Vec3 } from "./Vec3";

export interface VehicleUpdate { name: string, p: Vec3, q: Quat, asset_name: string, }